version: '3.8'
services:
  postgres:
    image: 'postgres:${POSTGRES_VERSION}'
    container_name: postgres
    hostname: postgres
    restart: always
    env_file:
      - .\database.env
    environment:
      - POSTGRES_DB:${POSTGRES_DB}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
#      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres:
    driver: local